'use client';
import { useEffect, useState } from 'react';
import { ArrowDownRight, ArrowRight, ArrowUpRight, Check, ChevronDown, FileText, Gauge, LayoutDashboard, Menu, Plus, Presentation, Printer, Save, SlidersHorizontal, X } from 'lucide-react';
import { Assumptions, Department, Hire, addMonths, currentPosition, monthDifference, project, runwayLabel } from '@/lib/model';
import { basePlan, FICTIONAL_NOTICE, presetOrder, roleSuggestions, scenarioPresets } from '@/lib/demo-data';
import { money, monthName, pct } from '@/lib/format';
import { BurnChart, CashChart, HeadcountChart, RevenueExpenseChart } from './charts';

type Section = 'overview' | 'lab' | 'decision' | 'brief';
const departments: Department[] = ['Engineering', 'Sales', 'Product', 'Customer Success', 'Operations'];
const sections: { id: Section; label: string; icon: typeof LayoutDashboard }[] = [
  { id: 'overview', label: 'Overview', icon: LayoutDashboard },
  { id: 'lab', label: 'Scenario Lab', icon: SlidersHorizontal },
  { id: 'decision', label: 'Decision', icon: Gauge },
  { id: 'brief', label: 'Decision Brief', icon: FileText },
];
function Logo({ small = false }: { small?: boolean }) { return <div className="brand"><span className="brand-mark"><i /><i /><i /></span>{!small && <span>DealZephyr<span className="brand-dot">.</span></span>}</div>; }
function Kpi({ label, value, detail, accent = false }: { label: string; value: string; detail?: string; accent?: boolean }) { return <div className="kpi"><div className="kpi-label">{label}</div><div className={accent ? 'kpi-value accent-text' : 'kpi-value'}>{value}</div>{detail && <div className="kpi-detail">{detail}</div>}</div>; }
function PanelTitle({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: React.ReactNode }) { return <div className="panel-title"><div>{eyebrow && <div className="eyebrow">{eyebrow}</div>}<h2>{title}</h2></div>{action}</div>; }
function NumberField({ label, value, onChange, prefix, suffix, step = 1, min = 0, max, hint }: { label: string; value: number; onChange: (n: number) => void; prefix?: string; suffix?: string; step?: number; min?: number; max?: number; hint?: string }) {
  return <label className="field"><span className="field-label">{label}</span><span className="number-wrap">{prefix && <span>{prefix}</span>}<input aria-label={label} type="number" value={value} min={min} max={max} step={step} onChange={e => onChange(Math.min(max ?? Infinity, Math.max(min, Number(e.target.value))))} />{suffix && <span>{suffix}</span>}</span>{hint && <small>{hint}</small>}</label>;
}
function RunwayDelta({ value, base }: { value: number | null; base: number | null }) {
  if (value === null || base === null) return <span className="delta neutral">Beyond model horizon</span>;
  const delta = value - base;
  return <span className={`delta ${delta < -0.05 ? 'negative' : delta > 0.05 ? 'positive' : 'neutral'}`}>{delta < -0.05 ? <ArrowDownRight size={15} /> : delta > 0.05 ? <ArrowUpRight size={15} /> : null}{delta >= 0 ? '+' : ''}{delta.toFixed(1)} months vs base plan</span>;
}
function Comparison({ selected, selectedName }: { selected: Assumptions; selectedName: string }) {
  const rows = presetOrder.map(name => ({ name, assumptions: scenarioPresets[name], result: project(scenarioPresets[name]) }));
  if (!scenarioPresets[selectedName] || JSON.stringify(selected) !== JSON.stringify(scenarioPresets[selectedName])) rows.unshift({ name: selectedName, assumptions: selected, result: project(selected) });
  const maxRunway = Math.max(...rows.map(r => r.result.runwayMonths ?? 36));
  return <div className="panel comparison-panel"><PanelTitle eyebrow="SIDE BY SIDE" title="Scenario comparison" action={<span className="tiny-note">12-month ending cash · projected runway</span>} />
    <div className="table-scroll"><table className="comparison-table"><thead><tr><th>Scenario</th><th>Runway</th><th>Ending cash</th><th>Month 1 burn</th><th>Headcount¹</th></tr></thead><tbody>{rows.map(r => <tr key={r.name} className={r.name === selectedName || r.name === 'Live scenario' ? 'selected-row' : ''}><td><div className="scenario-name"><span className="scenario-indicator" />{r.name}</div></td><td><div className="runway-cell"><b>{runwayLabel(r.result.runwayMonths)}</b><span className="mini-track"><span style={{ width: `${Math.min(100, (r.result.runwayMonths ?? 36) / maxRunway * 100)}%` }} /></span></div></td><td>{money(r.result.endingCash12)}</td><td>{money(r.result.months[0].netBurn)}</td><td>{r.result.months[11].headcount}</td></tr>)}</tbody></table></div><p className="footnote">¹ Headcount at month 12. A negative ending cash balance shows the gap that would need to be funded; the model continues to display the trajectory for comparison.</p></div>;
}
function ModelFlow() { return <div className="model-flow"><div className="flow-heading"><span className="eyebrow">THE DEALZEPHYR METHOD</span><h2>Make the decision before the spend.</h2></div><div className="flow-steps">{['Operating decision', 'Financial model', 'Scenarios', 'Cash · burn · runway', 'Decision'].map((step, i) => <div className="flow-step" key={step}><span>0{i + 1}</span><b>{step}</b>{i < 4 && <ArrowRight size={16} />}</div>)}</div></div>; }
function Sprint() { return <section className="sprint"><div><div className="eyebrow">HOW THE REAL ENGAGEMENT WORKS</div><h2>7-Day Finance<br />Decision Sprint<span>.</span></h2><p>In an engagement, we replace this fictional data with your company’s actual financial and operating inputs. The output is a decision you can act on, with the tradeoffs in view.</p><div className="sprint-price">$2,499 <span>fixed sprint price</span></div></div><div className="sprint-days">{[['01','Understand the decision and gather inputs'],['02–03','Build and review the operating model'],['04–05','Run scenarios and stress-test assumptions'],['06','Develop recommendations and decision brief'],['07','Founder readout']].map(([day, desc]) => <div key={day}><span>DAY {day}</span><b>{desc}</b></div>)}</div></section>; }
function OptionCard({ tag, title, description, value, base, cash, headcount, selected = false }: { tag: string; title: string; description: string; value: number | null; base: number | null; cash: number; headcount: number; selected?: boolean }) { return <div className={`option-card ${selected ? 'recommended' : ''}`}><div className="option-tag">{tag}{selected && <span>ILLUSTRATIVE PICK</span>}</div><h3>{title}</h3><p>{description}</p><div className="option-runway">{runwayLabel(value)} <span>projected runway</span></div><RunwayDelta value={value} base={base} /><div className="option-bottom"><span>12-month cash <b>{money(cash)}</b></span><span>Month 12 team <b>{headcount}</b></span></div></div>; }
function DecisionContent({ assumptions }: { assumptions: Assumptions }) {
  const hires = assumptions.hires;
  const immediate = { ...assumptions, hires: hires.map(h => ({ ...h, startMonth: assumptions.startingMonth })) };
  const staggered = { ...assumptions, hires: hires.map((h, i) => ({ ...h, startMonth: addMonths(assumptions.startingMonth, i % 4) })) };
  const delayed = { ...assumptions, hires: hires.map((h, i) => ({ ...h, startMonth: addMonths(assumptions.startingMonth, i < 2 ? 2 : 6 + i - 2) })) };
  const base = project(basePlan);
  const options = [project(immediate), project(staggered), project(delayed)];
  return <><div className="section-heading"><div className="eyebrow">DECISION / 01</div><h1>What can Auralane afford?</h1><p>How aggressively should Auralane execute its next {hires.length} hires? These options change hiring timing while holding the current revenue and cost assumptions constant.</p></div>
    <div className="decision-question"><span>THE OPERATING QUESTION</span><h2>Hire for the plan we want, or for the cash we have?</h2><p>Each option below flows through the same monthly model. The recommendation is illustrative demo content, not advice to a real company.</p></div>
    <div className="option-grid"><OptionCard tag="OPTION A" title="Hire immediately" description="Bring every planned role into payroll this month." value={options[0].runwayMonths} base={base.runwayMonths} cash={options[0].endingCash12} headcount={options[0].months[11].headcount} /><OptionCard tag="OPTION B" title="Stagger over 90 days" description="Sequence starts over four months as hiring capacity comes online." value={options[1].runwayMonths} base={base.runwayMonths} cash={options[1].endingCash12} headcount={options[1].months[11].headcount} selected /><OptionCard tag="OPTION C" title="Delay non-critical roles" description="Start two roles in month three; hold the others until months seven and eight." value={options[2].runwayMonths} base={base.runwayMonths} cash={options[2].endingCash12} headcount={options[2].months[11].headcount} /></div>
    <div className="decision-columns"><div className="panel editorial-panel"><div className="eyebrow">TRADEOFFS & RISKS</div><h2>The cash saved has an operating cost.</h2><ul><li><b>Faster hiring</b> supports delivery and pipeline capacity sooner, but locks in fixed costs before results are known.</li><li><b>Staggered hiring</b> creates checkpoints after early revenue and productivity signals.</li><li><b>Delays</b> protect cash, but may constrain product delivery or customer coverage.</li></ul></div><div className="panel editorial-panel"><div className="eyebrow">ILLUSTRATIVE DEMO RECOMMENDATION</div><h2>Stage commitments. Recheck the evidence.</h2><p>For this fictional company, begin with roles tied to near-term execution, then release later hires when bookings and cloud spend track to plan. If revenue misses, revisit the sequence before adding fixed payroll.</p><p className="microcopy">This is an example of DealZephyr’s decision process, not a recommendation for an actual client.</p></div></div>
  </>;
}
function DecisionBrief({ assumptions, onPrint }: { assumptions: Assumptions; onPrint: () => void }) {
  const result = project(assumptions), base = project(basePlan), current = currentPosition(assumptions);
  const variance = result.runwayMonths !== null && base.runwayMonths !== null ? result.runwayMonths - base.runwayMonths : null;
  return <><div className="brief-toolbar"><div><div className="eyebrow">SAMPLE DELIVERABLE</div><h1>Decision Brief</h1><p>A printable example generated from the live scenario.</p></div><button className="primary-button" onClick={onPrint}><Printer size={16} /> Print / save PDF</button></div>
    <article className="brief-sheet" id="decision-brief"><div className="brief-top"><Logo /><span>DECISION BRIEF / DEMO</span></div><div className="brief-intro"><div className="eyebrow">AURALANE SYSTEMS · {monthName(assumptions.startingMonth, false).toUpperCase()}</div><h1>How aggressively should Auralane execute its next {assumptions.hires.length} hires?</h1><p>Illustrative operating decision · Scenario: <b>{assumptions.name}</b></p></div>
      <div className="brief-callout"><span>EXECUTIVE SUMMARY</span><p>At {money(current.cash)} in cash and {money(current.burn)} of current monthly net burn, Auralane’s hiring sequence materially changes its cash trajectory. Under the selected assumptions, projected runway is <b>{runwayLabel(result.runwayMonths)}</b>{variance !== null ? ` (${variance >= 0 ? '+' : ''}${variance.toFixed(1)} months versus the base plan)` : ''}. The next commitment should be assessed alongside revenue performance and cash headroom.</p></div>
      <div className="brief-stats"><div><span>ARR</span><b>{money(current.arr)}</b></div><div><span>CASH</span><b>{money(current.cash)}</b></div><div><span>NET BURN TODAY</span><b>{money(current.burn)}</b></div><div><span>SELECTED RUNWAY</span><b>{runwayLabel(result.runwayMonths)}</b></div></div>
      <div className="brief-two"><section><h2>Decision being evaluated</h2><p>Whether to accelerate, stagger, or defer {assumptions.hires.length} planned hires while preserving enough cash to respond to a revenue miss.</p><h2>Key assumptions</h2><ul><li>MRR begins at {money(assumptions.startingMRR)} and grows {pct(assumptions.revenueGrowthPct)} monthly before a {pct(assumptions.revenueDownsidePct)} downside adjustment.</li><li>Core gross margin before cloud: {pct(assumptions.coreGrossMarginPct)}; cloud spend: {money(assumptions.cloudMonthly)}/month.</li><li>Other operating expenses: {money(assumptions.otherOpexMonthly)}/month; {assumptions.hires.length} scheduled hires.</li><li>{assumptions.fundraiseMonth ? `Illustrative fundraise: ${money(assumptions.fundraiseAmount)} in ${monthName(assumptions.fundraiseMonth)}.` : 'No future fundraise included.'}</li></ul></section><section><h2>Cash and runway implications</h2><div className="brief-metric"><span>Runway under current selection</span><b>{runwayLabel(result.runwayMonths)}</b></div><div className="brief-metric"><span>Cash after 12 months</span><b>{money(result.endingCash12)}</b></div><div className="brief-metric"><span>Month 12 headcount</span><b>{result.months[11].headcount}</b></div><div className="brief-metric"><span>Month 1 gross margin</span><b>{pct(result.months[0].grossMarginPct)}</b></div></section></div>
      <section className="brief-section"><h2>Scenario comparison</h2><table className="brief-table"><thead><tr><th>Scenario</th><th>Runway</th><th>12-month cash</th><th>Month 1 burn</th></tr></thead><tbody>{[['Base plan', base],['Selected scenario', result],['Revenue downside', project(scenarioPresets['Revenue Downside'])]].map(([label, p]) => { const proj = p as ReturnType<typeof project>; return <tr key={label as string}><td>{label as string}</td><td>{runwayLabel(proj.runwayMonths)}</td><td>{money(proj.endingCash12)}</td><td>{money(proj.months[0].netBurn)}</td></tr>; })}</tbody></table></section>
      <div className="brief-two closing"><section><h2>Key risks</h2><p>Revenue growth may not arrive on schedule; hiring can lag in productivity; cloud costs may rise with usage. Any of these would shorten the cash window.</p><h2>What would change the view</h2><p>Updated bookings, actual hiring dates and compensation, gross margin trends, and the timing or certainty of new capital.</p></section><section><h2>Illustrative recommendation</h2><p>Sequence hires against evidence of demand and delivery capacity. Re-run the model before each offer is accepted, especially after a revenue miss.</p><h2>Next actions</h2><p>Validate the role sequence, confirm a downside revenue case, and set a cash checkpoint before committing the final hires.</p></section></div>
      <div className="brief-footer"><span>DEALZEPHYR · YOUR FINANCE TEAM BEFORE YOU HIRE A FINANCE TEAM</span><span>01 / 01</span></div><p className="brief-disclaimer">{FICTIONAL_NOTICE} All figures and recommendations are illustrative demo content and are not financial advice.</p>
    </article></>;
}
function RunwayChart({ selected }: { selected: Assumptions }) {
  const items = [
    { label: 'Base plan', value: project(basePlan).runwayMonths },
    { label: 'Selected', value: project(selected).runwayMonths },
    { label: 'Downside', value: project(scenarioPresets['Hiring + Revenue Downside']).runwayMonths },
  ];
  const max = Math.max(12, ...items.map(i => i.value ?? 36));
  return <div className="runway-chart">{items.map((item, i) => <div className="runway-bar-row" key={i}><div><span>{item.label}</span><b>{runwayLabel(item.value)}</b></div><div className="runway-track"><span className={i === 1 ? 'active' : ''} style={{ width: `${Math.min(100, (item.value ?? 36) / max * 100)}%` }} /></div></div>)}</div>;
}
function Overview({ assumptions, selectedName, onGoLab, onGoDecision }: { assumptions: Assumptions; selectedName: string; onGoLab: () => void; onGoDecision: () => void }) {
  const projection = project(assumptions), base = project(basePlan), noHire = project({ ...basePlan, hires: [] }), current = currentPosition(assumptions);
  const m1 = projection.months[0];
  return <>
    <div className="overview-head"><div><div className="eyebrow">THE CURRENT PLAN / AURALANE SYSTEMS</div><h1>Decisions have<br /><em>a cash shape.</em></h1><p>See what happens when Auralane changes hiring pace, revenue, or cost assumptions. Every number below comes from the same monthly operating model.</p><button className="text-link" onClick={onGoLab}>Open Scenario Lab <ArrowRight size={16} /></button></div><div className="runway-hero"><span className="hero-caption">PROJECTED RUNWAY · {assumptions.name.toUpperCase()}</span><div className="hero-number">{runwayLabel(projection.runwayMonths)}</div><RunwayDelta value={projection.runwayMonths} base={base.runwayMonths} /><div className="hero-divider" /><p>Cash reaches zero based on projected monthly revenue, expenses and scheduled hiring. Without the four planned hires, the base model runs for <b>{runwayLabel(noHire.runwayMonths)}</b>.</p></div></div>
    <div className="kpi-grid"><Kpi label="ARR" value={money(current.arr)} detail="Current run rate" /><Kpi label="MRR" value={money(current.revenue)} detail="At model start" /><Kpi label="Cash" value={money(current.cash)} detail="Opening balance" /><Kpi label="Net burn" value={money(current.burn)} detail="Current month, before hires" accent /><Kpi label="Headcount" value={String(current.headcount)} detail="Employees today" /><Kpi label="Gross margin" value={pct(current.grossMarginPct)} detail="Current, incl. cloud" /><Kpi label="Monthly op. expenses" value={money(assumptions.currentPayroll + assumptions.otherOpexMonthly)} detail="Payroll + other opex" /><Kpi label="Planned hires" value={String(assumptions.hires.length)} detail="Scheduled in this scenario" /></div>
    <div className="chart-feature panel"><PanelTitle eyebrow="THE FINANCIAL CONSEQUENCE" title="Cash balance over time" action={<div className="chart-legend"><span><i className="legend-selected" />Selected</span><span><i className="legend-base" />Base plan</span></div>} /><CashChart months={projection.months} base={base.months} /><div className="chart-footer"><div><span>12-month ending cash</span><b>{money(projection.endingCash12)}</b></div><div><span>Month 1 net burn</span><b>{money(m1.netBurn)}</b></div><div><span>Month 12 team</span><b>{projection.months[11].headcount}</b></div><button onClick={onGoDecision}>View decision <ArrowRight size={15} /></button></div></div>
    <div className="chart-grid"><div className="panel chart-card"><PanelTitle eyebrow="PACE OF SPEND" title="Monthly net burn" /><BurnChart months={projection.months} /></div><div className="panel chart-card"><PanelTitle eyebrow="OPERATING TRAJECTORY" title="Revenue vs. expenses" action={<div className="chart-legend"><span><i className="legend-revenue" />Revenue</span><span><i className="legend-selected" />Expenses</span></div>} /><RevenueExpenseChart months={projection.months} /></div><div className="panel chart-card"><PanelTitle eyebrow="CAPACITY" title="Headcount over time" /><HeadcountChart months={projection.months} /></div><div className="panel chart-card"><PanelTitle eyebrow="TIME TO ZERO CASH" title="Runway" /><RunwayChart selected={assumptions} /></div></div>
    <Comparison selected={assumptions} selectedName={selectedName} />
    <section className="plan-section"><div className="plan-heading"><div><div className="eyebrow">THE INPUTS BEHIND THE OUTPUT</div><h2>Current operating plan</h2></div><button className="text-link" onClick={onGoLab}>Edit assumptions <ArrowRight size={15} /></button></div><div className="plan-grid"><div className="plan-card"><div className="eyebrow">01 / HIRING PLAN</div><h3>{assumptions.hires.length} planned roles</h3>{assumptions.hires.length ? assumptions.hires.map(h => <div className="plan-row" key={h.id}><span>{h.role}<small>{h.department}</small></span><b>{monthName(h.startMonth)}</b></div>) : <p>No hires currently scheduled.</p>}</div><div className="plan-card"><div className="eyebrow">02 / REVENUE ASSUMPTIONS</div><h3>Growth path</h3><div className="plan-row"><span>Starting MRR</span><b>{money(assumptions.startingMRR)}</b></div><div className="plan-row"><span>Monthly growth</span><b>{pct(assumptions.revenueGrowthPct)}</b></div><div className="plan-row"><span>Revenue downside</span><b>{pct(assumptions.revenueDownsidePct)}</b></div><div className="plan-row"><span>Core gross margin</span><b>{pct(assumptions.coreGrossMarginPct)}</b></div></div><div className="plan-card"><div className="eyebrow">03 / MAJOR COSTS</div><h3>Monthly commitments</h3><div className="plan-row"><span>Current payroll</span><b>{money(assumptions.currentPayroll)}</b></div><div className="plan-row"><span>Cloud infrastructure</span><b>{money(assumptions.cloudMonthly)}</b></div><div className="plan-row"><span>Other operating expenses</span><b>{money(assumptions.otherOpexMonthly)}</b></div><div className="plan-row"><span>Hires, once all started</span><b>{money(assumptions.hires.reduce((n,h) => n + h.monthlyCost, 0))}</b></div></div></div></section>
    <ModelFlow /><Sprint />
  </>;
}
function Lab({ assumptions, update, selectedName, onSave }: { assumptions: Assumptions; update: (fn: (a: Assumptions) => Assumptions) => void; selectedName: string; onSave: () => void }) {
  const projection = project(assumptions), base = project(basePlan);
  const change = <K extends keyof Assumptions>(key: K, value: Assumptions[K]) => update(a => ({ ...a, [key]: value }));
  const updateHire = (id: string, patch: Partial<Hire>) => update(a => ({ ...a, hires: a.hires.map(h => h.id === id ? { ...h, ...patch } : h) }));
  const setHireCount = (count: number) => update(a => { const next = [...a.hires]; const target = Math.max(0, Math.min(20, count)); while (next.length < target) { const suggestion = roleSuggestions[next.length % roleSuggestions.length]; next.push({ id: `hire-${Date.now()}-${next.length}`, role: suggestion.role, department: suggestion.department, startMonth: addMonths(a.startingMonth, 3 + next.length), monthlyCost: 9000 }); } return { ...a, hires: next.slice(0, target) }; });
  return <><div className="section-heading lab-heading"><div><div className="eyebrow">SCENARIO LAB / LIVE MODEL</div><h1>Change the plan.<br /><em>See the consequence.</em></h1><p>Adjust a single assumption and watch the cash view recalculate. Save a version when you want to compare it with the prepared scenarios.</p></div><button className="outline-button" onClick={onSave}><Save size={15} /> Save this scenario</button></div>
    <div className="lab-layout"><div className="lab-controls">
      <div className="control-group"><div className="control-heading"><span>01</span><h2>Revenue & margin</h2></div><div className="field-grid"><NumberField label="Monthly revenue growth" value={assumptions.revenueGrowthPct} onChange={v => change('revenueGrowthPct', v)} suffix="%" step={0.1} min={-20} max={30} hint="Compounds month over month" /><NumberField label="Revenue downside" value={assumptions.revenueDownsidePct} onChange={v => change('revenueDownsidePct', v)} suffix="%" step={1} max={100} hint="Applied to projected revenue" /><NumberField label="Core gross margin" value={assumptions.coreGrossMarginPct} onChange={v => change('coreGrossMarginPct', v)} suffix="%" step={0.5} max={100} hint="Before cloud infrastructure" /><NumberField label="Cloud / infrastructure" value={assumptions.cloudMonthly} onChange={v => change('cloudMonthly', v)} prefix="$" step={1000} hint="Monthly fixed cloud cost" /></div></div>
      <div className="control-group"><div className="control-heading"><span>02</span><h2>Cash & operating costs</h2></div><div className="field-grid"><NumberField label="Current cash" value={assumptions.startingCash} onChange={v => change('startingCash', v)} prefix="$" step={10000} /><NumberField label="Other operating expenses" value={assumptions.otherOpexMonthly} onChange={v => change('otherOpexMonthly', v)} prefix="$" step={1000} hint="Excludes payroll and COGS" /></div></div>
      <div className="control-group"><div className="control-heading"><span>03</span><h2>Hiring plan</h2></div><div className="hiring-summary"><NumberField label="Number of planned hires" value={assumptions.hires.length} onChange={setHireCount} step={1} min={0} max={20} /><span>{money(assumptions.hires.reduce((n, h) => n + h.monthlyCost, 0))}/mo when all roles start</span></div>
        <div className="hire-list">{assumptions.hires.map((hire, i) => <div className="hire-card" key={hire.id}><div className="hire-head"><span>ROLE {String(i + 1).padStart(2, '0')}</span><button title={`Remove ${hire.role}`} aria-label={`Remove ${hire.role}`} onClick={() => update(a => ({ ...a, hires: a.hires.filter(h => h.id !== hire.id) }))}><X size={15} /></button></div><div className="hire-fields"><label className="field"><span className="field-label">Role</span><input aria-label="Role" type="text" value={hire.role} onChange={e => updateHire(hire.id, { role: e.target.value })} /></label><label className="field"><span className="field-label">Department</span><span className="select-wrap"><select aria-label="Department" value={hire.department} onChange={e => updateHire(hire.id, { department: e.target.value as Department })}>{departments.map(d => <option key={d}>{d}</option>)}</select><ChevronDown size={14} /></span></label><label className="field"><span className="field-label">Start month</span><input aria-label="Start month" type="month" min={assumptions.startingMonth} value={hire.startMonth} onChange={e => { if (e.target.value) updateHire(hire.id, { startMonth: e.target.value }); }} /></label><NumberField label="Fully loaded / month" value={hire.monthlyCost} onChange={v => updateHire(hire.id, { monthlyCost: v })} prefix="$" step={500} /></div></div>)}</div><button className="add-hire" onClick={() => setHireCount(assumptions.hires.length + 1)}><Plus size={15} /> Add role</button></div>
      <div className="control-group"><div className="control-heading"><span>04</span><h2>Optional fundraising</h2></div><label className="toggle-row"><span><b>Include a future raise</b><small>New cash arrives at the start of the selected month.</small></span><input type="checkbox" checked={assumptions.fundraiseMonth !== null} onChange={e => update(a => ({ ...a, fundraiseMonth: e.target.checked ? addMonths(a.startingMonth, 9) : null, fundraiseAmount: e.target.checked ? (a.fundraiseAmount || 2_000_000) : 0 }))} /><i /></label>{assumptions.fundraiseMonth && <div className="field-grid raise-fields"><label className="field"><span className="field-label">Fundraise month</span><input aria-label="Fundraise month" type="month" min={assumptions.startingMonth} value={assumptions.fundraiseMonth} onChange={e => { if (e.target.value) change('fundraiseMonth', e.target.value); }} /></label><NumberField label="Amount" value={assumptions.fundraiseAmount} onChange={v => change('fundraiseAmount', v)} prefix="$" step={100000} /></div>}</div>
    </div><div className="lab-output"><div className="live-card"><div className="live-top"><span><i className="live-dot" /> LIVE CONSEQUENCE</span><b>{selectedName}</b></div><div className="live-runway">{runwayLabel(projection.runwayMonths)}<span>projected runway</span></div><RunwayDelta value={projection.runwayMonths} base={base.runwayMonths} /><div className="live-metrics"><div><span>12-month cash</span><b>{money(projection.endingCash12)}</b></div><div><span>Month 1 burn</span><b>{money(projection.months[0].netBurn)}</b></div><div><span>Month 12 team</span><b>{projection.months[11].headcount}</b></div><div><span>Month 1 gross margin</span><b>{pct(projection.months[0].grossMarginPct)}</b></div><div><span>Month 1 gross profit</span><b>{money(projection.months[0].grossProfit)}</b></div><div><span>Month 1 expenses</span><b>{money(projection.months[0].expenses)}</b></div></div></div><div className="panel lab-chart"><PanelTitle eyebrow="SELECTED VS. BASE" title="Cash trajectory" /><CashChart months={projection.months} base={base.months} compact /><p>Cash is rolled forward month by month. The dotted line is the base plan.</p>{assumptions.fundraiseMonth && projection.runwayMonths !== null && monthDifference(assumptions.startingMonth, assumptions.fundraiseMonth) >= projection.runwayMonths && <p className="raise-warning">The selected raise occurs after projected cash reaches zero, so it does not extend calculated runway.</p>}</div><div className="panel lab-chart"><PanelTitle eyebrow="HIRING IMPACT" title="Headcount" /><HeadcountChart months={projection.months} /></div></div></div>
    <Comparison selected={assumptions} selectedName={selectedName} />
  </>;
}
export default function Dashboard() {
  const [section, setSection] = useState<Section>('overview');
  const [presenting, setPresenting] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [saved, setSaved] = useState<Record<string, Assumptions>>({});
  const [storageReady, setStorageReady] = useState(false);
  const [activeKey, setActiveKey] = useState('Base Plan');
  const [draft, setDraft] = useState<Assumptions>(basePlan);
  const [saveOpen, setSaveOpen] = useState(false);
  const [saveName, setSaveName] = useState('');
  // Custom scenarios remain local to this browser. No account or database is involved.
  useEffect(() => { try { setSaved(JSON.parse(localStorage.getItem('dealzephyr-scenarios') || '{}') as Record<string, Assumptions>); } catch { setSaved({}); } setStorageReady(true); }, []);
  useEffect(() => { if (storageReady) localStorage.setItem('dealzephyr-scenarios', JSON.stringify(saved)); }, [saved, storageReady]);
  const scenarios = { ...scenarioPresets, ...saved };
  const edited = JSON.stringify(draft) !== JSON.stringify(scenarios[activeKey]);
  const selectedName = edited ? 'Live scenario' : activeKey;
  const selectScenario = (name: string) => { setActiveKey(name); setDraft(structuredClone(scenarios[name])); setMobileOpen(false); };
  const update = (fn: (a: Assumptions) => Assumptions) => setDraft(a => fn(a));
  const saveScenario = () => { const name = saveName.trim(); if (!name) return; const next = { ...draft, name }; setSaved(old => ({ ...old, [name]: next })); setActiveKey(name); setDraft(next); setSaveName(''); setSaveOpen(false); };
  const navigate = (next: Section) => { setSection(next); setMobileOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  return <div className={`app-shell ${presenting ? 'presentation-mode' : ''}`}>
    <aside className={`sidebar ${mobileOpen ? 'open' : ''}`}><div className="sidebar-brand"><Logo /><button className="mobile-close" onClick={() => setMobileOpen(false)} aria-label="Close menu"><X size={20} /></button></div><div className="sidebar-inner"><div className="side-overline">THE WORKSPACE</div><nav className="side-nav">{sections.map(s => { const Icon = s.icon; return <button key={s.id} className={section === s.id ? 'active' : ''} onClick={() => navigate(s.id)}><Icon size={17} strokeWidth={1.8} />{s.label}{section === s.id && <span className="nav-mark" />}</button>; })}</nav><div className="side-divider" /><div className="side-overline">PREPARED SCENARIOS</div><div className="side-scenarios">{presetOrder.map(name => <button key={name} className={activeKey === name ? 'active' : ''} onClick={() => selectScenario(name)}><span className="scenario-indicator" />{name}</button>)}{Object.keys(saved).length > 0 && <><div className="side-overline saved-label">YOUR SAVED VIEWS</div>{Object.keys(saved).map(name => <button key={name} className={activeKey === name ? 'active' : ''} onClick={() => selectScenario(name)}><span className="scenario-indicator" />{name}</button>)}</>}</div></div><div className="sidebar-foot"><span>DEALZEPHYR / SALES DEMO</span><small>Fictional company · October 2026</small></div></aside>
    <div className="main-area"><header className="topbar"><div className="top-left"><button className="mobile-menu" aria-label="Open menu" onClick={() => setMobileOpen(true)}><Menu size={20} /></button><span className="top-divider" /><span className="top-context">AURALANE SYSTEMS <span>/</span> {section === 'overview' ? 'OVERVIEW' : section === 'lab' ? 'SCENARIO LAB' : section === 'decision' ? 'DECISION' : 'DECISION BRIEF'}</span></div><div className="top-actions"><span className="demo-pill"><i /> FICTIONAL DEMO</span><button className={`presentation-button ${presenting ? 'active' : ''}`} onClick={() => { setPresenting(v => !v); setSection('overview'); }}><Presentation size={16} />{presenting ? 'Exit presentation' : 'Presentation mode'}</button></div></header>
      <div className="fiction-banner"><span>ILLUSTRATIVE COMPANY</span><p>{FICTIONAL_NOTICE}</p></div>
      {presenting && <div className="presenter-bar"><span>SWITCH THE DECISION</span><div>{['Base Plan', 'Aggressive Hiring', 'Delayed Hiring', 'Revenue Downside', 'Hiring + Revenue Downside'].map(name => <button key={name} className={activeKey === name ? 'active' : ''} onClick={() => selectScenario(name)}>{name === 'Base Plan' ? 'Base' : name === 'Revenue Downside' ? 'Downside' : name === 'Hiring + Revenue Downside' ? 'Hire + downside' : name}</button>)}</div><button className="presenter-edit" onClick={() => { setPresenting(false); navigate('lab'); }}>Edit assumptions <ArrowRight size={14} /></button></div>}
      <main className="content">{section === 'overview' && <Overview assumptions={draft} selectedName={selectedName} onGoLab={() => navigate('lab')} onGoDecision={() => navigate('decision')} />}{section === 'lab' && <Lab assumptions={draft} selectedName={selectedName} update={update} onSave={() => { setSaveName(`${draft.name} — custom`); setSaveOpen(true); }} />}{section === 'decision' && <DecisionContent assumptions={draft} />}{section === 'brief' && <DecisionBrief assumptions={draft} onPrint={() => window.print()} />}</main>
      <footer className="app-footer"><Logo /><p>Your finance team before you hire a finance team.</p><span>FICTIONAL DEMO · NOT CLIENT RESULTS</span></footer>
    </div>
    {saveOpen && <div className="modal-backdrop" onMouseDown={() => setSaveOpen(false)}><div className="save-modal" role="dialog" aria-modal="true" aria-label="Save scenario" onMouseDown={e => e.stopPropagation()}><button className="modal-x" onClick={() => setSaveOpen(false)} aria-label="Close"><X size={18} /></button><div className="eyebrow">KEEP THIS VERSION</div><h2>Save scenario</h2><p>Saved in this browser for your next demo.</p><label className="field"><span className="field-label">Scenario name</span><input autoFocus value={saveName} onChange={e => setSaveName(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') saveScenario(); }} /></label>{presetOrder.includes(saveName.trim()) && <p className="name-warning">Choose a name other than a prepared scenario.</p>}<button className="primary-button" disabled={!saveName.trim() || presetOrder.includes(saveName.trim())} onClick={saveScenario}><Check size={16} /> Save scenario</button></div></div>}
  </div>;
}
